version: '3.9'

services:
  bin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET=a.out
    container_name: bin
  unit_tests:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET=unit_tests
    container_name: unit_tests