name: Build Check

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Check
    env:
      TARGET: a.out
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: a.out
          - os: ubuntu-latest
            target: a.out
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2

      - name: Create build folder
        run: mkdir -p build

      - name: Build project
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --target ${{ matrix.bin }}
        working-directory: ./build
